import Head from 'next/head'
import { Counter } from '../features/counter/counter'

const About = () => {
    return (
        <>
        <Head>
        <title>eShop Well - About Us</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
            <h1>About Us</h1>
            <Counter />
        </>
    )
};

export default About;

