import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useDispatch, useSelector } from 'react-redux'
import type { RootState } from '../store'
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();

  const aboutUs = () => router.push('about')

  return (
    <>
      <Head>
        <title>eShop Well - Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <h1>Hello Next js</h1>
        <button onClick={aboutUs}> About Us </button>
        
      </main>
    </>
  )
}

